version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai_backend
    env_file:
      - /home/secrets/tg-ai-agent.env
    ports:
      - "8085:8000"
    restart: always

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: telegram_bot
    env_file:
      - /home/secrets/tg-ai-agent.env
    depends_on:
      - backend
    restart: always
